apiVersion: apps/v1
kind: Deployment
metadata:
  name: htrung-deploy
  namespace: deploy-argocd
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: dckb9xz/todo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: htrung-svc
  namespace: deploy-argocd
spec:
  selector:
    app: todo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#       nodePort: 30132